name = "kimba-hairstylist-crm"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "kimba.ch/*", zone_name = "kimba.ch" }
]

[[env.production.rules]]
type = "Text"
globs = ["**/*.html"]
[env.production.rules.result]
"Cache-Control" = "public, max-age=0, must-revalidate"

[[env.production.rules]]
type = "Text" 
globs = ["**/*.json"]
[env.production.rules.result]
"Content-Type" = "application/json"
"Cache-Control" = "public, max-age=300"

[[env.production.rules]]
type = "Text"
globs = ["**/*.css"]
[env.production.rules.result]
"Content-Type" = "text/css"
"Cache-Control" = "public, max-age=31536000"

[[env.production.rules]]
type = "Text"
globs = ["**/*.js"]
[env.production.rules.result]
"Content-Type" = "application/javascript"
"Cache-Control" = "public, max-age=31536000"