import type { DashboardConfiguration } from '../types';

export const DEFAULT_DASHBOARD_CONFIG: DashboardConfiguration = {
  widgets: [
    {
      id: 'today-revenue',
      type: 'today-revenue',
      title: "Today's Revenue",
      position: { x: 0, y: 0, order: 0 },
      size: { width: 3, height: 1 },
      isVisible: true,
    },
    {
      id: 'monthly-revenue',
      type: 'monthly-revenue',
      title: 'Monthly Revenue',
      position: { x: 3, y: 0, order: 1 },
      size: { width: 3, height: 1 },
      isVisible: true,
    },
    {
      id: 'today-appointments',
      type: 'today-appointments',
      title: "Today's Appointments",
      position: { x: 6, y: 0, order: 2 },
      size: { width: 3, height: 1 },
      isVisible: true,
    },
    {
      id: 'ai-generations',
      type: 'ai-generations',
      title: 'AI Generations',
      position: { x: 9, y: 0, order: 3 },
      size: { width: 3, height: 1 },
      isVisible: true,
    },
    {
      id: 'revenue-chart',
      type: 'revenue-chart',
      title: 'Revenue Chart',
      position: { x: 0, y: 1, order: 4 },
      size: { width: 6, height: 3 },
      isVisible: true,
    },
    {
      id: 'average-price-trend',
      type: 'average-price-trend',
      title: 'Average Price Trend',
      position: { x: 6, y: 1, order: 5 },
      size: { width: 6, height: 3 },
      isVisible: true,
    },
    {
      id: 'quick-actions',
      type: 'quick-actions',
      title: 'Quick Actions',
      position: { x: 0, y: 4, order: 6 },
      size: { width: 3, height: 2 },
      isVisible: true,
    },
    {
      id: 'recent-bookings',
      type: 'recent-bookings',
      title: 'Recent Bookings',
      position: { x: 3, y: 4, order: 7 },
      size: { width: 3, height: 2 },
      isVisible: true,
    },
    {
      id: 'sticky-notes',
      type: 'sticky-notes',
      title: 'Sticky Notes',
      position: { x: 6, y: 4, order: 8 },
      size: { width: 6, height: 2 },
      isVisible: true,
    },
    {
      id: 'recent-lookbooks',
      type: 'recent-lookbooks',
      title: 'Recent Lookbooks',
      position: { x: 0, y: 6, order: 9 },
      size: { width: 12, height: 2 },
      isVisible: true,
    },
  ],
  gridCols: 12,
  gridRows: 10,
  version: 2,
};
